### PR TITLE
Add/iri

### PR DESCRIPTION
**Pull request by nuriel77**
- Install IRI container
- Configure paths
- Configure firewalls
- Add util scripts

### CODE REVIEW

**Comment by nuriel77** [comment]
I recommend testing this branch first:
```
git clone -b add/iri https://github.com/nuriel77/nelson.cli
```
Need to have a look into the networking, whether to use host networking or a different option.

**Comment by rosstimson** [comment]
@nuriel77 Awesome work on the Ansible stuff so far.  My only thoughts about this one is I'd much prefer to stick to official Docker images where one exists.  I know the current IRI image isn't great from a config perspective at the moment but hopefully PRs to rectify this will be merged soon.

For the networking, I think we should be creating a proper Docker network rather than relying upon `--net host`, I'm pretty sure using the host network is discouraged.  So we could have something like:

```
docker network create iota
docker run --net iota .........
```

Then the containers can be referenced by their names.  The only problem I've encountered with this is the IRI official image restricts the neighbour commands that Nelson needs when using the API remotely (i.e. via inter-container networking rather than localhost) and therefore we need to remove those default filters.  This of course causes a security concern.  In AWS (I normally use) I figured I'd just not open the API port up in the security group and if I needed it I'd use an SSH tunnel.  Perhaps you can think of a better solution though.

I hope to test this Ansible work out over the next evening or so.  Keep up the great work, many of us appreciate it.

**Comment by nuriel77** [comment]
Hi @rosstimson , thanks.

I realize work still has to be done to improve this. I also prefer to use official Docker images, but I didn't get it working due to missing configuration options. Hence why I used an image I've created (which is based on the official one). 

Regarding the networking, I realize that host network is discourage when a node has to separate the host services from colliding with services running in the containers.

I am trying to find the right way to use internal docker network using ansible. I managed to create a custom network and add containers to it.

I will keep on playing around with this. I was trying to follow this example:
https://github.com/ansible/awx/blob/b06a508cebd035fb2a1e85f60568ef1c1c0030dd/installer/local_docker/tasks/main.yml
Which actually works (I have this running somewhere), although they are using links which are going to be deprecated soon IIRC.

I am mostly experienced with Kubernetes, where you create a pod of multiple containers. Containers share the same 127.0.0.1 interface - they can reach eachother using 127.0.0.1:<service port> which would be ideal for us because it would by-pass the remote-limite-api limitation.

I wish to find a way to do that with docker.

**Comment by nuriel77** [comment]
@rosstimson Ok, I got it working without host networking. Now creating an isolated network for iri and nelson to share.

**Comment by nuriel77** [comment]
I managed to have nelson and iri share the same network namespace, meaning that nelson can now access iri via 127.0.0.1:14265 and is not restricted by commands.

That resolves the issue of nelson being restricted for remote commands.
However, this will still be a problem -- for example when a user wants to run curl commands on the host to IRI.

After having tested all these networking options I believe that using host network is the best solution as it allows for everything to work without problems.
Most users are not going to run conflicting services on their host, so it should not pose a problem anyway.

**Comment by romansemko** [comment]
Looks good to me, but I am not experienced with Ansible. Someone has to review, nevertheless. @rosstimson, any objections from your side?

**Comment by rosstimson** [comment]
@nuriel77 Understood, so you believe host networking is best option after investigating the isolated network option.  As well as port clashes I'd guess host networking is discouraged for security reasons, but the fact we have to weaken security by removing the IRI API filters when not using the the host network option probably makes that reason a moot point.  Are you going to revert your recent change which removed the host networking then?

@romansemko The Ansible looked good to me, I think Nuriel might be wanting to change back to the original networking before this is merged though.

**Comment by nuriel77** [comment]
Yes, I will revert it now.

Indeed, the API port will be exposed on the host. However, the user will have to open the port in the firewall to allow connections to it. Not as secure as having had IRI run on the host bind 127.0.0.1, but I don't see more options at the moment.

**Comment by nuriel77** [comment]
Please test (I tested on fresh Centos 7.4, ubuntu 16 and 17)

I made it optional to choose if to expose IRI API port (by default it will listen on localhost and firewall not opened for its port)

Need to think what is the best way to maintain deployments: for example, the iri.ini and nelson's config ini I've set ansible to install once and never overwrite, so that users changes are not thrown away.

It is Ansible's (or any other config's tool) philosophy that you should never configure deployed files manually but do it via the playbook.

What are your thoughts on this?

**Pull request merged**
